coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
query.max-memory=5GB
query.max-memory-per-node=1GB
discovery-server.enabled=true
discovery.uri=http://localhost:8080


# coordinator=true
# node-scheduler.include-coordinator=true
# http-server.http.port=8080
# query.max-memory=5GB
# query.max-memory-per-node=1GB
# discovery-server.enabled=true
# discovery.uri=http://localhost:8080

# # Password authentication
# http-server.authentication.type=PASSWORD
# password-authenticator.file=/etc/trino/password.db
